### PR TITLE
feat: add NG assets for dev environment

### PR DESCRIPTION
**Pull request by jvitor03**

### CODE REVIEW

**Comment by L30Bola** [comment]
As we discussed in private, I think the specific Tilt modules directories should be added on `.gitignore`, so adding `tilt_modules/restart_process` should be enough.

**Comment by L30Bola** [comment]
For the rest, must we commit the CRDs and CRs?

**Comment by jvitor03** [comment]
> For the rest, must we commit the CRDs and CRs?

Yes, the CRs are an idempotent alternative for cluster-api init
And the CRDs are examples to be populated in the kind, also an alternative to cluster-api generate

finally, both CRs and CRDs also have the kops clusters/NGs that are inexistent in the cluster-api project

**Review by L30Bola — APPROVED** [review]
After the discussion, LGTM!

**Pull request merged**
